pipeline {
    agent any
    environment {
      github = credentials('github')
      dockerhub = credentials('dockerhub')
    }
     stages {
        stage('build') {
          when {
            allOf {
            changeset "jenkins-example/web-frontend/**"
            not { changeset pattern: "Jenkinsfile" }
            }
        }
           steps {
               sh '''
                 until docker container ls ; do sleep 3 ;done && docker build -t ${dockerhub_USR}/customer-info:web-frontend-${GIT_COMMIT} ./jenkins-example/customers/
                 docker login -u ${dockerhub_USR} -p ${dockerhub_PSW} && docker push ${dockerhub_USR}/customer-info:web-frontend-${GIT_COMMIT}
                 '''
           }
        }
       stage('deploy') {
        
          when {
            allOf {
            changeset "jenkins-example/web-frontend/**"
            not { changeset pattern: "Jenkinsfile" }
            }
          }

           steps {
               sh '''
                     git config --global user.email "khanshehbaz104@gmail.com" 
                     git checkout jenkins-argocd
                     export image_tag="${dockerhub_USR}/customer-info:web-frontend-${GIT_COMMIT}" 
                     yq eval '.spec.template.spec.containers[0].image = env(image_tag)' -i ./jenkins-example/manifests/web-frontend.yaml
                     git add . 
                     git commit -m "Updated image tag for web-frontend" 
                     git push https://${github_USR}:${github_PSW}@github.com/shehbaz-pathan/simple-microservices-app.git
                  '''
             
           }
       }

     }
}
