apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers
  labels:
    app: customers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers
      version: v2
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: 6255/customer-info:customers-0dbeb94fca2c2c612b9d84394fa1205fb1d2c06a
          imagePullPolicy: Always
          name: svc
          ports:
            - containerPort: 3000
